# Generated by Django 5.0.6 on 2024-07-22 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('verification', models.BooleanField(default=False)),
                ('reset_token', models.CharField(blank=True, max_length=128, null=True)),
                ('reset_token_expiration', models.DateTimeField(blank=True, null=True)),
                ('activation_token', models.CharField(blank=True, max_length=128, null=True)),
                ('activation_token_expiration', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(default='user', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
