# Generated by Django 5.0.6 on 2024-07-22 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_login',
        ),
    ]
