# Generated by Django 5.1.4 on 2025-01-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_license_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='expiry_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
