# Generated by Django 5.1.4 on 2025-01-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_license_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
