# Generated by Django 5.1.4 on 2025-01-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_license_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='expiry_date',
            field=models.DateField(default=2023),
            preserve_default=False,
        ),
    ]
