# Generated by Django 5.1.4 on 2025-01-02 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_license_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='license',
            name='expiry_date',
        ),
    ]
